spring:
  application:
    name: bitlyClone

  datasource:
    name: bitlyClone
    url: jdbc:h2:./data/bitlyClone.db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  threads:
    virtual:
      enabled: true

jwt-config:
  secret: ${JWT_SECRET}
